local keymap = vim.keymap
keymap.set("n", "<leader>e", ":Neotree toggle<CR>", { silent = true })
keymap.set("n", "<leader>ff", ":Telescope find_files<CR>", { silent = true })
keymap.set("n", "<leader>fg", ":Telescope live_grep<CR>", { silent = true })
keymap.set("n", "<leader>ss", function()
  require("telescope.builtin").lsp_document_symbols()
end, { desc = "Search document symbols", silent = true })
keymap.set("n", "<leader>sS", function()
  require("telescope.builtin").lsp_dynamic_workspace_symbols()
end, { desc = "Search workspace symbols", silent = true })
